#+TITLE: Quicksilver M2TW Manual
#+AUTHOR: Linus Arver
#+STARTUP: indent showall

* Overview
- There are many changes to speed up gameplay and to make things feel much more dynamic and fluid. The primary aim has been to remove repetitive actions as much as possible.
* Full list of changes from vanilla M2TW (with 1.3 patch)
** Campaign map
*** Unit speed
- Campaign movement speed 1.75x for all units
- Ship movement speed 3x (3x the 1.75x)
- Diplomat movement speed 2x (2x the 1.75x)
*** Initial provinces and buildings
- Give paved roads for all settlements.
  - Durazzo, the only undefined settlement (which default to a village in-game) in descr_strat.txt, gets an entry in descr_strtat.txt to allow this.
- Gold/silver mines for capitals and secondary provinces (if any); see Finances section
*** Agents
- Disable diplomacy animations from the campaign map; specifically, the `conduct diplomacy' and bowing animations have been removed
- Remove merchants (too much micro-management).
- Remove princesses (use diplomats instead).
- Remove spies (use assassins instead; spies are over-powered anyway with their 'open gate' ability).
- Remove heretics, witches, and inquisitors.
**** Assassins
- Increase effectiveness 2x
- Increase base chance of success from 5% to 17% (1 out of 6, just like rolling a single die, to help newbie assassins)
- Increase max chance of success to from 95% to 99%
- Minimum success chance changed from 5% to 17% (1 out of 6, just like rolling a die; so a newbie assassin should be able to succeed more easily), and maximum chance changed from 95% to 99%
- Recruitment cost 3x
- Upkeep cost 3x
- Give good assassins a line of sight bonus with increased skill, to emulate spies.
*** Other
- Rebel spawn rate 20x lower
- Pirate spawn rate 20x lower
** Guilds
- No spies, so remove Thieves' Guild
- Bugfix: give swordsmiths guild HQ a heavy cavalry bonus 2, instead of 1 (which is the bonus level of master swordsmiths guild)
** Settlement defenses
- City/Castle defense tower activation range 8x
- Walls and gate HP 5x
- Tower HP 2x
- Tower firing rate at all levels 2x
  - Exception: Flaming arrows, flaming ballistas, and cannons (both regular and flaming) remain at default settings
** Buildings
- All building constructions take 1 turn
- Remove farms; farm capabilities have been merged into walls (the wall upgrades when transitioning into a larger town/city).
- Remove taverns; tavern capabilities have been merged into markets.
- Remove sea trade buildings (merchant's wharf, etc.); their capabilities have been merged into ports.
- Remove gunpowder and world_is_round requirements for advanced port buildings (drydocks and dockyards).
  - NOTE: However, ocean-capable ships (carracks+) are not recruitable until the world_is_round event.
- Reduce city/castle population upgrade requirements. For both cities and castles, there are more reductions for smaller settlements. See `Settlement mechanics'.
- The more expensive the building, the more it costs. See the comment in the export_descr_buildings.txt file for details. The cheapest building (which costs 400) is the same, but the most expensive ones cost almost 2x more.
- No spies, so disable all Thieves' Guild buildings
** Recruitment
- Give free upkeep slots to castles (1, 2, 3, 4, and 5)
- All free upkeep slots 2x (castles stacked)
- Increase recruitment slots from [city: 1, 2, 2, 3, 3] [castle: 1, 2, 3, 3, 3] to [city: 1, 2, 3, 4, 5] [castle: 2, 3, 4, 5, 6]
- Basic infantry have free upkeep (mental up to 5 AND cost up to 650)
- For each building type (walls, barracks, stables, ports, etc.), let all levels of that building recruit the same units. However, we give the more advanced buildings bonuses to base unit number, recruitment points gained per turn, maximum recruitment points available, and (most importantly) the starting experience.
- Allow a settlement to recruit 2 agents of the same type in a single turn.
- Fix Swordsmiths Guild HQ bonuses bug (vanilla did not give any extra bonsues for getting the HQ level; now it grants 1 more extra bonus point for factionwide heavy_cavalry_bonus (experience of knights)).
*** Mercenaries
- Mercenaries cost 1.25x
- Mercenaries replenishment rate 3x
- Mercenaries pool initial 5x
- Mercenaries pool max 5x
** Units
- Bodyguard soldiers (cavalry and infantry types) reduced 0.5x; costs reduced accordingly
- Missile infantry ammo 2x
- Pikemen units: fix rubber swords bug (pikemen only use pikes, not their weak secondary swords)
** Finance
- King's purse 2x
- Moors' King's purse 1.5x
- Turks' King's purse 1.5x
- Egypt's King's purse 1.75x
- Remove corruption trigger based on high treasury (characters do not gain any negative penalties for having a large treasury)
- No merchants (also, no Merchant's Guild)
*** Gold/silver-only mining
- Only gold and silver are mineable.
- All existing gold and silver resources on the main campaign map (not New World) have been replaced with chocolate and silk, respectively. Each faction now has 1 gold resource at its capital and 1 silver resource at its secondary region (or both at capital if the faction starts out with only 1 region).
- All factions start out with pre-built mines in their capitals and secondary regions (if any).
  - Thus, mines cannot be built any more by the player, as all the places that could possibly build mines already start out with a mine.
- The point of this mod is to make each faction's capital and secondary region (if applicable) very valuable. There is an incentive to take an enemy faction's capital before taking their other settlements, for example. It also levels the playing field for those factions without valuable mineable resources, because gold and silver are no longer concentrated in regions like Zagreb/Vienna.
- Gold and silver mines make 3000 and 1500 florins each, respectively.
- To reinforce the idea that gold/silver can only benefit the owner of the region, their trade value has been drastically reduced (to 2 and 1, respectively).
- The New World regions still have all of their gold/silver resources, which makes them extremely valuable. Vanilla M2TW made taking the New World regions very boring, but now at least there is an incentive (lots of money!).
- For kicks, Rome has 3 gold resources! This makes capturing Rome very tempting...
- The redundant ``Mining Network'' building has been removed, since the regular mines alone make enough money.
** Settlement mechanics
- Reduce ``distance to capital'' penalty by 75%
- Reduce ``religious unrest'' penalty by 50%
- Reduce population requirements to upgrade a settlement, such that smaller settlements can get upgraded more quickly. This will help prevent settlements from stagnating as villages and towns (or mottes/baileys). The smaller populations get more population upgrade reductions than the bigger ones.
** Missions
- Disable all mission penalties (play the game with free will --- no more harassment from the Pope/Council)
- Disable the annoying ``cease hostilities'' mission
- Reduce successful assassination payback from 10 assassins guild points to 5, to make it harder to get the Assassins' Guild improvements.
- Increase every mission's monetary reward (the higher the reward, the greater the increase); see descr_missions.txt for details.
- Fix council_min/mod_money bug in descr_missions.txt (the lines starting with ''    cash ...'' were not correctly mapped to their intended paybacks)
  - Also, increase the cash threshold 10x for triggering the major/mod/min money rewards (since this mod's other modifications make it so that the player has a large cash reserve most of the time).
- Increase every mission's monetary reward with formula (NEW = OLD + (((OLD - 100)/100) * 2000)). See descr_missions.txt for a tabular breakdown.
- Increase every mission's military reward 3x
- Decrease every mission's duration by 33% (except for the ``convert'' mission where you have to convert a settlement's religion)
- No spies, so disable all Thieves' Guild missions
- No merchants, so disable all Merchants' Guild missions
** Game AI
- Fixed faction standing bug (where sacking a settlement would give you a higher reputation than peacefully occupying it)
- Papal States no longer capture rebel settlements (helps land-strapped factions like Milan and Sicily expand into Africa more easily)
*** Powerful Rebels
- Starting money of 5,000,000 florins (vanilla 5000)
- 500,000 florins gained per turn (vanilla 500)
- Change AI behavior type to `default' just like all the other non-catholic factions
** Other
- Unlock all playable factions
- Disable forced combat closeups (gate/wall is destroyed or enemy general is killed)
- Allow unlimited men on the battlefield (i.e., all armies (main armies + reinforcments) can enter the battle map at the same time)
